api:
  autodiscoveryId: "123456"  

http:
  host: "0.0.0.0"
  port: "8085"
  
https:
  host: "0.0.0.0"
  port: "8086"

database:
  host: "65.2.46.226"
  port: "3306"
  user: "mulepoc_user"
  db: "mulepoc"
  
tls:
  type: "JKS"
  path: "KeyStore.jks"
  alias: "mulesoft"
