#%RAML 1.0 SecurityScheme
type: x- client id enforment
description: Client ID Enforcement
describedBy:
  headers:
    client_id:
      type: string
      required: true
    client_secret:
      type: string
      required: true