#%RAML 1.0 Trait

displayName: Source System
description: Details of the source system
headers:
  systemId:
    description: System Identification Number
    displayName: System Id
    type: string
    required: false
    example: "GDIA1234544"